version: "3"
services:
    postgres:
        image: postgres
        container_name: finance-app-pg
        environment:
            POSTGRES_PASSWORD: password
            POSGRES_USER: root
            POSGRES_DB: finance-app
        ports:
            - "5432:5432"
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
